# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e386179dfc2122d9eadb75edaee6faa796da931e9b113f111ba2fdde9558634f4a11c7b1e9155e1e81c1004f50885adda8c50fcd14e9f3799166785c1c147f15

test:
  secret_key_base: c2c53bf2129d0882e11f157be0d4875d732f8dd90478c66718c2a488afc428ea7058f2a99675bdfd288afc96c0f6390f0ef77c0f63b186fd7500cceb139b226f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
